name: Firebase Deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 18

    - name: Install dependencies
      run: npm install

    - name: Install Firebase CLI
      run: npm install -g firebase-tools

    - name: Set GOOGLE_APPLICATION_CREDENTIALS
      run: echo "${{ secrets.GOOGLE_APPLICATION_CREDENTIALS }}" > $HOME/firebase-key.json
      env:
        GOOGLE_APPLICATION_CREDENTIALS: ${{ secrets.GOOGLE_APPLICATION_CREDENTIALS }}

    - name: Deploy to Firebase
      env:
        GOOGLE_APPLICATION_CREDENTIALS: $HOME/firebase-key.json
      run: firebase deploy --only hosting:my-app